# db configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=testkhedu
spring.datasource.password=testkhedu

# mybatis configuration
mybatis.type-aliases-package=com.kh.khedu.dto,com.kh.khedu.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.mapper-locations=/mybatis/**/*-mapper.xml

# logging
logging.level.root=warn
logging.level.com.kh=debug
logging.level.mapper=debug
logging.pattern.console=[%-5level] %msg -%c -%d{yyyy-MM-dd HH:mm:ss} %n 

# multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# custom configuration
# 1.email information
custom.email.host=smtp.gmail.com
custom.email.port=587
custom.email.username=tookwak4
custom.email.password= vkfpokiugmzlufcd
custom.email.from=tookwak4@gmail.com

# jwt
custom.jwt.issuer=https://www.khacademy.co.kr/
custom.jwt.secret=12345678901234567890123456789012
# cookie
custom.jwt.access-token-validity=1800
custom.jwt.refresh-token-validity=2419200

# login
custom.login.need-update-term=30

# storage
custom.storage.local=D:/upload
custom.storage.aws-region=ap-northeast-2
custom.storage.aws-bucket=kh17-storage-951322694876-ap-northeast-2-an
custom.storage.aws-root=uploads
custom.storage.presigned-limit=10

# kakaopay
custom.kakaopay.secret-key=DEV7666CCB40C0DA849EDC018AC9FB809D3F93F7
custom.kakaopay.cid=TC0ONETIME